name: Download and Merge IP Addresses

on:
  push:  # 每当有新代码推送到存储库时触发
    branches:
      - main  # 可以根据需要更改分支名称

jobs:
  merge_ips:
    runs-on: ubuntu-latest  # 使用最新版的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码到工作目录

      - name: Download and Merge IPs
        run: |
          wget -r --no-parent -A "*.txt" "https://github.com/hello-earth/cloudflare-better-ip/tree/main/cloudflare"
          cat ./github.com/hello-earth/cloudflare-better-ip/tree/main/cloudflare/*.txt | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" > ip.txt
          rm -rf github.com

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"
          git add ip.txt
          git commit -m "Update IP addresses [skip ci]"
          git push
